### PR TITLE
Enabled custom routing

### PR DESCRIPTION
**Pull request by eduardoarandah**
related to this pull request
Laravel-Backpack/Base#156

### CODE REVIEW

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/Base/issues/131 will also address this...

**Comment by tabacitu** [comment]
Hi @eduardoarandah ,

Thanks for the PR, but I think this no longer applies, since we have a uniform way of overwriting the routes file now (woohooo!!!). Check out:
- [the howto here](https://github.com/Laravel-Backpack/LogManager#overwriting-functionality)
- [the commit here](https://github.com/Laravel-Backpack/LogManager/commit/7d31f0aedb477fa28d84f212c7ae05d1360fcd17)

Cheers!

**Comment by eduardoarandah** [comment]
@tabacitu great!

Would be great to add an "routes" argument to make it automatically like: 

`php artisan backpack:routes --controller=SomethingController`

And have nice named routes 

Also, sometimes, the view is not enough, so 

`php artisan backpack:view --view=something.index`

with the base structure 

```
@extend('backpack:layout')
@section('before_scripts')
@append
@section('content')
@endsection
@section('after_scripts')
@append
```

I'll try to find time to make a prototype for this

**Comment by lloy0076** [comment]
@eduardoarandah - wouldn't it be better to add those suggestions either as an enhancement issue or on an issue that isn't closed, or the PR that could add them? 😈

**Comment by eduardoarandah** [comment]
@lloy0076 

jaja yes 
let me find where do I enhacement button

travolta

**Comment by lloy0076** [comment]
Make an issue and if you can't mark it as an enhancement, mention me and I will!

**Pull request closed without merging**
